Add setConfig method and use prebid configuration
scm-spain/OpenAds-appnexus-prebid pull request #4
Opened 2019-01-14 13:43 UTC by pablovegau

# Background

From Appnexus arrived a request to change the configuration that we send to Prebid.

# Goal

Add new parameters to the Prebid configuration

# Implementation

- Add new setConfig method to PrebidClient

# Checklist

- [ ] The PR relates to *only* one subject with a clear title.
- [ ] I have performed a self-review of my own code
- [ ] Wrote [good commit messages](http://chris.beams.io/posts/git-commit/)
- [ ] My code is readable by someone else, and I commented the hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# Visual description

*your meme goes here*
![](https://media.giphy.com/media/xT5LMVjsPH3wn2EXYc/giphy.gif)

2019-01-14 14:26 UTC, alextremp requested changes

2019-01-14 14:26 UTC, alextremp commented on src/openads-appnexus/PrebidClientImpl.js
> +    this._logger.debug(this._logger.name, '| setConfig has been called.')
'setConfig has been called' seems a copy paste of the debug line of a method that receives no args :trollface: 
Maybe this one should log the received config?

2019-01-14 15:27 UTC, pablovegau commented on src/openads-appnexus/PrebidClientImpl.js
> +    this._logger.debug(this._logger.name, '| setConfig has been called.')
done! :D

2019-01-15 11:19 UTC, alextremp approved these changes

2019-01-15 11:19 UTC, alextremp commented
👍 
Please, update de README docs

2019-01-15 11:38 UTC, merged